spring.application.name=laboratorio

# Lee desde variables de entorno, con valores por defecto para desarrollo local
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.profiles.active=dev

server.port=${PORT:8080}
