spring.application.name=laboratorio

# Lee desde variables de entorno, con valores por defecto para desarrollo local
spring.datasource.url=${DB_URL:jdbc:mysql://gateway01.us-east-1.prod.aws.tidbcloud.com:4000/productodb}
spring.datasource.username=${DB_USER:3aaRKCBViscBzBB.root}
spring.datasource.password=${DB_PASS:WtJfctG9qXUoLZx7}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.profiles.active=dev